name: nlp_healthcare
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - jupyter
  - python-dotenv
  - tqdm
  # data
  - pandas
  - numpy
  # ML
  - scikit-learn
  - tensorflow
  - scipy
  - nltk
  - spacy
  - transformers
  # graphics
  - matplotlib
  - plotly
  - seaborn
  - tabulate
pip:
  - huggingface
  - torch
  - jupytext