#!/usr/bin/env bash


#SBATCH -A SNIC2022-22-1040 -p alvis
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --gpus-per-node=T4:1
#SBATCH --job-name=nlp_healthcare_kb_bert
#SBATCH -o /cephyr/users/rlucas/Alvis/nlp_healthcare/outputs/KB_BERT.out
#SBATCH -t 00:30:00

# Remove any already loaded modules
module purge
module load Python/3.10.8-GCCcore-12.2.0-bare


#Load env
source env/bin/activate

#Set file name
NOTEBOOK=kb_bert


python /cephyr/users/rlucas/Alvis/nlp_healthcare/notebooks_models/model_scripts/${NOTEBOOK}.py