#!/usr/bin/env bash


#SBATCH -A SNIC2022-22-1040 -p alvis
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --gpus-per-node=T4:1
#SBATCH --job-name=nlp_healthcare_multi
#SBATCH -o /cephyr/users/rlucas/Alvis/nlp_healthcare/outputs/BIO_BERT_%a.out
#SBATCH -t 00:30:00

# Remove any already loaded modules
module purge

#Load env
source env/bin/activate

#Set file name
NOTEBOOK=bio_bert

python /cephyr/users/rlucas/Alvis/nlp_healthcare/notebooks_models/${NOTEBOOK}.py ${SLURM_ARRAY_TASK_ID}